name: Latest release

on:
  push:
    branches:
      - 'main'
    
jobs:       
  unit_tests:
    uses: ./.github/workflows/unit_tests.yml

  deploy_main_nuget:
    uses: ./.github/workflows/deploy_nuget.yml
    needs: [ unit_tests ]
    with:
      project-name: src/Environment.Setup
      version-fragment: 'feature'
      nuget-name: 'environment.setup'
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
